### ISSUE TITLE
Docstrings overhaul

### ISSUE THREAD

**Issue by jonstrutz11** [KShebek/MINE-Database#14]
Ensure docstrings are all correct (have all arguments and return values documented)

convert existing docstrings to NumPy format.

**Edit:** 

@jonstrutz11 Assigning files:

Kevin
- [x] reactions.py
- [x] databases.py
- [x] pickaxe.py
- [x] utils.py
- [x] My part of filters.py

Jon
- [x] compound_io.py
- [x] metabolomics.py
- [x] queries.py
- [x] Your part of filters.py

**Comment by KShebek** [comment]
Closing this out -- all docstrings are done!
